name: myproweb
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_info_plus: ^11.2.0
  injectable:  ^2.5.0
  get_it:  ^8.0.3
  dio: ^5.7.0
  auto_route: ^9.2.2
  connectivity_plus: ^6.1.1
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_video: ^1.0.5
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.10
  provider: ^6.1.2
  flutter_dotenv: ^5.2.1
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.5
  flex_color_scheme: ^8.1.0
  adaptive_theme: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator:  ^2.6.2
  build_runner: ^2.4.14
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
  assets:
    - .env
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700